name: Angular

on:
- push

jobs:
  build-and-deploy:
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Build
      run: |
        npm install
        npm run build -- --configuration production

    - name: Deploy
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.SSH_HOST_KEY }}" >> ~/.ssh/known_hosts
        eval $(ssh-agent -s)
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        rsync -r --delete dist/Website/ print3dcloud@server.makerepo.com:/var/www/print3dcloud/frontend/

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Lint
      run: |
        npm install
        npm run lint
